// flow-typed signature: fd46737ebcf0f7181f5a761706938d30
// flow-typed version: <<STUB>>/airbnb-js-shims_v^1.0.1/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'airbnb-js-shims'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'airbnb-js-shims' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'airbnb-js-shims/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'airbnb-js-shims/index' {
  declare module.exports: $Exports<'airbnb-js-shims'>;
}
declare module 'airbnb-js-shims/index.js' {
  declare module.exports: $Exports<'airbnb-js-shims'>;
}
declare module 'airbnb-js-shims/test/index.js' {
  declare module.exports: $Exports<'airbnb-js-shims/test/index'>;
}
