// flow-typed signature: 655448ad664e53411f86cba7efd5cd11
// flow-typed version: <<STUB>>/babel-preset-es2016_v6.11.3/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-es2016'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-es2016' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-es2016/index' {
  declare module.exports: $Exports<'babel-preset-es2016'>;
}
declare module 'babel-preset-es2016/index.js' {
  declare module.exports: $Exports<'babel-preset-es2016'>;
}
