// flow-typed signature: 2342a6c810d78db8bcd1a32813e500e7
// flow-typed version: <<STUB>>/changelog-verify_v^1.0.4/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'changelog-verify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'changelog-verify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'changelog-verify/cli' {
  declare module.exports: any;
}

declare module 'changelog-verify/scripts/version-changelog' {
  declare module.exports: any;
}

declare module 'changelog-verify/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'changelog-verify/cli.js' {
  declare module.exports: $Exports<'changelog-verify/cli'>;
}
declare module 'changelog-verify/index' {
  declare module.exports: $Exports<'changelog-verify'>;
}
declare module 'changelog-verify/index.js' {
  declare module.exports: $Exports<'changelog-verify'>;
}
declare module 'changelog-verify/scripts/version-changelog.js' {
  declare module.exports: $Exports<'changelog-verify/scripts/version-changelog'>;
}
declare module 'changelog-verify/test/test.js' {
  declare module.exports: $Exports<'changelog-verify/test/test'>;
}
