// flow-typed signature: 47e60bbea8b7150c2c0d71f82be0ac65
// flow-typed version: <<STUB>>/eslint-loader_v1.4.1/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-loader/index' {
  declare module.exports: $Exports<'eslint-loader'>;
}
declare module 'eslint-loader/index.js' {
  declare module.exports: $Exports<'eslint-loader'>;
}
