// flow-typed signature: e2c1a6d2b16bef9957ff0ce077b2e750
// flow-typed version: <<STUB>>/eslint-import-resolver-webpack_v0.4.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-import-resolver-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-import-resolver-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-import-resolver-webpack/config' {
  declare module.exports: any;
}

declare module 'eslint-import-resolver-webpack/coverage/prettify' {
  declare module.exports: any;
}

declare module 'eslint-import-resolver-webpack/coverage/sorter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-import-resolver-webpack/config.js' {
  declare module.exports: $Exports<'eslint-import-resolver-webpack/config'>;
}
declare module 'eslint-import-resolver-webpack/coverage/prettify.js' {
  declare module.exports: $Exports<'eslint-import-resolver-webpack/coverage/prettify'>;
}
declare module 'eslint-import-resolver-webpack/coverage/sorter.js' {
  declare module.exports: $Exports<'eslint-import-resolver-webpack/coverage/sorter'>;
}
declare module 'eslint-import-resolver-webpack/index' {
  declare module.exports: $Exports<'eslint-import-resolver-webpack'>;
}
declare module 'eslint-import-resolver-webpack/index.js' {
  declare module.exports: $Exports<'eslint-import-resolver-webpack'>;
}
