// flow-typed signature: fe2fdb4670352340edfb3c310388588a
// flow-typed version: <<STUB>>/gw2e-item-attributes_v^1.2.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gw2e-item-attributes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gw2e-item-attributes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gw2e-item-attributes/build/combinationAttributes' {
  declare module.exports: any;
}

declare module 'gw2e-item-attributes/build/helpers' {
  declare module.exports: any;
}

declare module 'gw2e-item-attributes/build/index' {
  declare module.exports: any;
}

declare module 'gw2e-item-attributes/build/parseCharacter' {
  declare module.exports: any;
}

declare module 'gw2e-item-attributes/build/parseCombination' {
  declare module.exports: any;
}

declare module 'gw2e-item-attributes/build/parseItems' {
  declare module.exports: any;
}

declare module 'gw2e-item-attributes/build/parseString' {
  declare module.exports: any;
}

declare module 'gw2e-item-attributes/build/scaling' {
  declare module.exports: any;
}

declare module 'gw2e-item-attributes/build/static/attributes' {
  declare module.exports: any;
}

declare module 'gw2e-item-attributes/build/static/combinations' {
  declare module.exports: any;
}

declare module 'gw2e-item-attributes/tests/combinationAttributes.spec' {
  declare module.exports: any;
}

declare module 'gw2e-item-attributes/tests/helpers.spec' {
  declare module.exports: any;
}

declare module 'gw2e-item-attributes/tests/index.spec' {
  declare module.exports: any;
}

declare module 'gw2e-item-attributes/tests/parseCharacter.spec' {
  declare module.exports: any;
}

declare module 'gw2e-item-attributes/tests/parseCombination.spec' {
  declare module.exports: any;
}

declare module 'gw2e-item-attributes/tests/parseItems.spec' {
  declare module.exports: any;
}

declare module 'gw2e-item-attributes/tests/parseString.spec' {
  declare module.exports: any;
}

declare module 'gw2e-item-attributes/tests/scaling.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gw2e-item-attributes/build/combinationAttributes.js' {
  declare module.exports: $Exports<'gw2e-item-attributes/build/combinationAttributes'>;
}
declare module 'gw2e-item-attributes/build/helpers.js' {
  declare module.exports: $Exports<'gw2e-item-attributes/build/helpers'>;
}
declare module 'gw2e-item-attributes/build/index.js' {
  declare module.exports: $Exports<'gw2e-item-attributes/build/index'>;
}
declare module 'gw2e-item-attributes/build/parseCharacter.js' {
  declare module.exports: $Exports<'gw2e-item-attributes/build/parseCharacter'>;
}
declare module 'gw2e-item-attributes/build/parseCombination.js' {
  declare module.exports: $Exports<'gw2e-item-attributes/build/parseCombination'>;
}
declare module 'gw2e-item-attributes/build/parseItems.js' {
  declare module.exports: $Exports<'gw2e-item-attributes/build/parseItems'>;
}
declare module 'gw2e-item-attributes/build/parseString.js' {
  declare module.exports: $Exports<'gw2e-item-attributes/build/parseString'>;
}
declare module 'gw2e-item-attributes/build/scaling.js' {
  declare module.exports: $Exports<'gw2e-item-attributes/build/scaling'>;
}
declare module 'gw2e-item-attributes/build/static/attributes.js' {
  declare module.exports: $Exports<'gw2e-item-attributes/build/static/attributes'>;
}
declare module 'gw2e-item-attributes/build/static/combinations.js' {
  declare module.exports: $Exports<'gw2e-item-attributes/build/static/combinations'>;
}
declare module 'gw2e-item-attributes/tests/combinationAttributes.spec.js' {
  declare module.exports: $Exports<'gw2e-item-attributes/tests/combinationAttributes.spec'>;
}
declare module 'gw2e-item-attributes/tests/helpers.spec.js' {
  declare module.exports: $Exports<'gw2e-item-attributes/tests/helpers.spec'>;
}
declare module 'gw2e-item-attributes/tests/index.spec.js' {
  declare module.exports: $Exports<'gw2e-item-attributes/tests/index.spec'>;
}
declare module 'gw2e-item-attributes/tests/parseCharacter.spec.js' {
  declare module.exports: $Exports<'gw2e-item-attributes/tests/parseCharacter.spec'>;
}
declare module 'gw2e-item-attributes/tests/parseCombination.spec.js' {
  declare module.exports: $Exports<'gw2e-item-attributes/tests/parseCombination.spec'>;
}
declare module 'gw2e-item-attributes/tests/parseItems.spec.js' {
  declare module.exports: $Exports<'gw2e-item-attributes/tests/parseItems.spec'>;
}
declare module 'gw2e-item-attributes/tests/parseString.spec.js' {
  declare module.exports: $Exports<'gw2e-item-attributes/tests/parseString.spec'>;
}
declare module 'gw2e-item-attributes/tests/scaling.spec.js' {
  declare module.exports: $Exports<'gw2e-item-attributes/tests/scaling.spec'>;
}
