// flow-typed signature: a169e8f5461cc2e22f0a7729c623fd21
// flow-typed version: <<STUB>>/gw2itemstats_v^0.0.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gw2itemstats'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gw2itemstats' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gw2itemstats/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gw2itemstats/dist/index.js' {
  declare module.exports: $Exports<'gw2itemstats/dist/index'>;
}
