// flow-typed signature: 92db109767f9a7d08780a72933dbf0d2
// flow-typed version: <<STUB>>/install_v^0.10.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'install'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'install' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'install/install' {
  declare module.exports: any;
}

declare module 'install/install.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'install/install.js' {
  declare module.exports: $Exports<'install/install'>;
}
declare module 'install/install.min.js' {
  declare module.exports: $Exports<'install/install.min'>;
}
