// flow-typed signature: 63ef57d3037db958a37f9f8d382049d7
// flow-typed version: <<STUB>>/jsdom-global_v^2.1.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsdom-global'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsdom-global' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsdom-global/browser' {
  declare module.exports: any;
}

declare module 'jsdom-global/keys' {
  declare module.exports: any;
}

declare module 'jsdom-global/register' {
  declare module.exports: any;
}

declare module 'jsdom-global/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsdom-global/browser.js' {
  declare module.exports: $Exports<'jsdom-global/browser'>;
}
declare module 'jsdom-global/index' {
  declare module.exports: $Exports<'jsdom-global'>;
}
declare module 'jsdom-global/index.js' {
  declare module.exports: $Exports<'jsdom-global'>;
}
declare module 'jsdom-global/keys.js' {
  declare module.exports: $Exports<'jsdom-global/keys'>;
}
declare module 'jsdom-global/register.js' {
  declare module.exports: $Exports<'jsdom-global/register'>;
}
declare module 'jsdom-global/test.js' {
  declare module.exports: $Exports<'jsdom-global/test'>;
}
