// flow-typed signature: c83136a9dddc3ae4e29f990ef14baf47
// flow-typed version: <<STUB>>/less-vars-loader_v^1.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'less-vars-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'less-vars-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'less-vars-loader/index' {
  declare module.exports: $Exports<'less-vars-loader'>;
}
declare module 'less-vars-loader/index.js' {
  declare module.exports: $Exports<'less-vars-loader'>;
}
