// flow-typed signature: 35285f67223632e53399ec24fb76b6de
// flow-typed version: <<STUB>>/manup_v^1.0.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'manup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'manup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'manup/index' {
  declare module.exports: $Exports<'manup'>;
}
declare module 'manup/index.js' {
  declare module.exports: $Exports<'manup'>;
}
