// flow-typed signature: e0c9a942a888601369c232f9b2a622d1
// flow-typed version: <<STUB>>/name-all-modules-plugin_v^1.0.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'name-all-modules-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'name-all-modules-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'name-all-modules-plugin/index' {
  declare module.exports: $Exports<'name-all-modules-plugin'>;
}
declare module 'name-all-modules-plugin/index.js' {
  declare module.exports: $Exports<'name-all-modules-plugin'>;
}
