// flow-typed signature: 232e18a7459d7a538e8dad38e38f06dc
// flow-typed version: <<STUB>>/pixel-average_v^1.0.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pixel-average'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pixel-average' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pixel-average/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pixel-average/index' {
  declare module.exports: $Exports<'pixel-average'>;
}
declare module 'pixel-average/index.js' {
  declare module.exports: $Exports<'pixel-average'>;
}
declare module 'pixel-average/test.js' {
  declare module.exports: $Exports<'pixel-average/test'>;
}
