// flow-typed signature: 0819ed9c5c40813e4c47401e63375b9e
// flow-typed version: <<STUB>>/promise-loader_v^1.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promise-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'promise-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'promise-loader/index' {
  declare module.exports: $Exports<'promise-loader'>;
}
declare module 'promise-loader/index.js' {
  declare module.exports: $Exports<'promise-loader'>;
}
