// flow-typed signature: aade872afd55c1e9913d69e8e902e375
// flow-typed version: <<STUB>>/react-sticky-header_v^0.1.8/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-sticky-header'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-sticky-header' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-sticky-header/index.es6' {
  declare module.exports: any;
}

declare module 'react-sticky-header/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-sticky-header/index.es6.js' {
  declare module.exports: $Exports<'react-sticky-header/index.es6'>;
}
declare module 'react-sticky-header/index' {
  declare module.exports: $Exports<'react-sticky-header'>;
}
declare module 'react-sticky-header/index.js' {
  declare module.exports: $Exports<'react-sticky-header'>;
}
declare module 'react-sticky-header/index.umd.js' {
  declare module.exports: $Exports<'react-sticky-header/index.umd'>;
}
