// flow-typed signature: 116c729139b944d5cdd1bd33abb572b4
// flow-typed version: <<STUB>>/react-responsive_v^1.3.4/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-responsive'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-responsive' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-responsive/dist/react-responsive' {
  declare module.exports: any;
}

declare module 'react-responsive/dist/react-responsive.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-responsive/dist/react-responsive.js' {
  declare module.exports: $Exports<'react-responsive/dist/react-responsive'>;
}
declare module 'react-responsive/dist/react-responsive.min.js' {
  declare module.exports: $Exports<'react-responsive/dist/react-responsive.min'>;
}
