// flow-typed signature: dd3448f4fb6347558b66feb3a224cc33
// flow-typed version: <<STUB>>/redux-freeze_v^0.1.5/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-freeze'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-freeze' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-freeze/lib/middleware' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-freeze/lib/middleware.js' {
  declare module.exports: $Exports<'redux-freeze/lib/middleware'>;
}
