// flow-typed signature: 4956ad628c6f3336f07bdfeec7e9f3a2
// flow-typed version: <<STUB>>/rollbar_v^2.2.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollbar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollbar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollbar/browserstack.browsers' {
  declare module.exports: any;
}

declare module 'rollbar/defaults' {
  declare module.exports: any;
}

declare module 'rollbar/dist/plugins/jquery.min' {
  declare module.exports: any;
}

declare module 'rollbar/dist/rollbar' {
  declare module.exports: any;
}

declare module 'rollbar/dist/rollbar.min' {
  declare module.exports: any;
}

declare module 'rollbar/dist/rollbar.named-amd' {
  declare module.exports: any;
}

declare module 'rollbar/dist/rollbar.named-amd.min' {
  declare module.exports: any;
}

declare module 'rollbar/dist/rollbar.noconflict.umd' {
  declare module.exports: any;
}

declare module 'rollbar/dist/rollbar.noconflict.umd.min' {
  declare module.exports: any;
}

declare module 'rollbar/dist/rollbar.snippet' {
  declare module.exports: any;
}

declare module 'rollbar/dist/rollbar.umd' {
  declare module.exports: any;
}

declare module 'rollbar/dist/rollbar.umd.min' {
  declare module.exports: any;
}

declare module 'rollbar/Gruntfile' {
  declare module.exports: any;
}

declare module 'rollbar/karma.conf' {
  declare module.exports: any;
}

declare module 'rollbar/src/api' {
  declare module.exports: any;
}

declare module 'rollbar/src/apiUtility' {
  declare module.exports: any;
}

declare module 'rollbar/src/browser/bundles/rollbar' {
  declare module.exports: any;
}

declare module 'rollbar/src/browser/bundles/rollbar.noconflict' {
  declare module.exports: any;
}

declare module 'rollbar/src/browser/bundles/rollbar.snippet' {
  declare module.exports: any;
}

declare module 'rollbar/src/browser/detection' {
  declare module.exports: any;
}

declare module 'rollbar/src/browser/errorParser' {
  declare module.exports: any;
}

declare module 'rollbar/src/browser/globalSetup' {
  declare module.exports: any;
}

declare module 'rollbar/src/browser/logger' {
  declare module.exports: any;
}

declare module 'rollbar/src/browser/plugins/jquery' {
  declare module.exports: any;
}

declare module 'rollbar/src/browser/predicates' {
  declare module.exports: any;
}

declare module 'rollbar/src/browser/rollbar' {
  declare module.exports: any;
}

declare module 'rollbar/src/browser/rollbarWrapper' {
  declare module.exports: any;
}

declare module 'rollbar/src/browser/shim' {
  declare module.exports: any;
}

declare module 'rollbar/src/browser/snippet_callback' {
  declare module.exports: any;
}

declare module 'rollbar/src/browser/telemetry' {
  declare module.exports: any;
}

declare module 'rollbar/src/browser/transforms' {
  declare module.exports: any;
}

declare module 'rollbar/src/browser/transport' {
  declare module.exports: any;
}

declare module 'rollbar/src/browser/url' {
  declare module.exports: any;
}

declare module 'rollbar/src/notifier' {
  declare module.exports: any;
}

declare module 'rollbar/src/queue' {
  declare module.exports: any;
}

declare module 'rollbar/src/rateLimiter' {
  declare module.exports: any;
}

declare module 'rollbar/src/rollbar' {
  declare module.exports: any;
}

declare module 'rollbar/src/server/logger' {
  declare module.exports: any;
}

declare module 'rollbar/src/server/parser' {
  declare module.exports: any;
}

declare module 'rollbar/src/server/predicates' {
  declare module.exports: any;
}

declare module 'rollbar/src/server/rollbar' {
  declare module.exports: any;
}

declare module 'rollbar/src/server/transforms' {
  declare module.exports: any;
}

declare module 'rollbar/src/server/transport' {
  declare module.exports: any;
}

declare module 'rollbar/src/telemetry' {
  declare module.exports: any;
}

declare module 'rollbar/src/transforms' {
  declare module.exports: any;
}

declare module 'rollbar/src/utility' {
  declare module.exports: any;
}

declare module 'rollbar/test/api.test' {
  declare module.exports: any;
}

declare module 'rollbar/test/apiUtility.test' {
  declare module.exports: any;
}

declare module 'rollbar/test/browser.predicates.test' {
  declare module.exports: any;
}

declare module 'rollbar/test/browser.rollbar.test' {
  declare module.exports: any;
}

declare module 'rollbar/test/browser.transforms.test' {
  declare module.exports: any;
}

declare module 'rollbar/test/browser.transport.test' {
  declare module.exports: any;
}

declare module 'rollbar/test/browser.url.test' {
  declare module.exports: any;
}

declare module 'rollbar/test/notifier.test' {
  declare module.exports: any;
}

declare module 'rollbar/test/queue.test' {
  declare module.exports: any;
}

declare module 'rollbar/test/rateLimiter.test' {
  declare module.exports: any;
}

declare module 'rollbar/test/server.predicates.test' {
  declare module.exports: any;
}

declare module 'rollbar/test/server.rollbar.test' {
  declare module.exports: any;
}

declare module 'rollbar/test/server.transforms.test' {
  declare module.exports: any;
}

declare module 'rollbar/test/server.transport.test' {
  declare module.exports: any;
}

declare module 'rollbar/test/telemetry.test' {
  declare module.exports: any;
}

declare module 'rollbar/test/transforms.test' {
  declare module.exports: any;
}

declare module 'rollbar/test/utility.test' {
  declare module.exports: any;
}

declare module 'rollbar/vendor/JSON-js/cycle' {
  declare module.exports: any;
}

declare module 'rollbar/vendor/JSON-js/json_parse_state' {
  declare module.exports: any;
}

declare module 'rollbar/vendor/JSON-js/json_parse' {
  declare module.exports: any;
}

declare module 'rollbar/vendor/JSON-js/json2' {
  declare module.exports: any;
}

declare module 'rollbar/vendor/JSON-js/json3' {
  declare module.exports: any;
}

declare module 'rollbar/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollbar/browserstack.browsers.js' {
  declare module.exports: $Exports<'rollbar/browserstack.browsers'>;
}
declare module 'rollbar/defaults.js' {
  declare module.exports: $Exports<'rollbar/defaults'>;
}
declare module 'rollbar/dist/plugins/jquery.min.js' {
  declare module.exports: $Exports<'rollbar/dist/plugins/jquery.min'>;
}
declare module 'rollbar/dist/rollbar.js' {
  declare module.exports: $Exports<'rollbar/dist/rollbar'>;
}
declare module 'rollbar/dist/rollbar.min.js' {
  declare module.exports: $Exports<'rollbar/dist/rollbar.min'>;
}
declare module 'rollbar/dist/rollbar.named-amd.js' {
  declare module.exports: $Exports<'rollbar/dist/rollbar.named-amd'>;
}
declare module 'rollbar/dist/rollbar.named-amd.min.js' {
  declare module.exports: $Exports<'rollbar/dist/rollbar.named-amd.min'>;
}
declare module 'rollbar/dist/rollbar.noconflict.umd.js' {
  declare module.exports: $Exports<'rollbar/dist/rollbar.noconflict.umd'>;
}
declare module 'rollbar/dist/rollbar.noconflict.umd.min.js' {
  declare module.exports: $Exports<'rollbar/dist/rollbar.noconflict.umd.min'>;
}
declare module 'rollbar/dist/rollbar.snippet.js' {
  declare module.exports: $Exports<'rollbar/dist/rollbar.snippet'>;
}
declare module 'rollbar/dist/rollbar.umd.js' {
  declare module.exports: $Exports<'rollbar/dist/rollbar.umd'>;
}
declare module 'rollbar/dist/rollbar.umd.min.js' {
  declare module.exports: $Exports<'rollbar/dist/rollbar.umd.min'>;
}
declare module 'rollbar/Gruntfile.js' {
  declare module.exports: $Exports<'rollbar/Gruntfile'>;
}
declare module 'rollbar/karma.conf.js' {
  declare module.exports: $Exports<'rollbar/karma.conf'>;
}
declare module 'rollbar/src/api.js' {
  declare module.exports: $Exports<'rollbar/src/api'>;
}
declare module 'rollbar/src/apiUtility.js' {
  declare module.exports: $Exports<'rollbar/src/apiUtility'>;
}
declare module 'rollbar/src/browser/bundles/rollbar.js' {
  declare module.exports: $Exports<'rollbar/src/browser/bundles/rollbar'>;
}
declare module 'rollbar/src/browser/bundles/rollbar.noconflict.js' {
  declare module.exports: $Exports<'rollbar/src/browser/bundles/rollbar.noconflict'>;
}
declare module 'rollbar/src/browser/bundles/rollbar.snippet.js' {
  declare module.exports: $Exports<'rollbar/src/browser/bundles/rollbar.snippet'>;
}
declare module 'rollbar/src/browser/detection.js' {
  declare module.exports: $Exports<'rollbar/src/browser/detection'>;
}
declare module 'rollbar/src/browser/errorParser.js' {
  declare module.exports: $Exports<'rollbar/src/browser/errorParser'>;
}
declare module 'rollbar/src/browser/globalSetup.js' {
  declare module.exports: $Exports<'rollbar/src/browser/globalSetup'>;
}
declare module 'rollbar/src/browser/logger.js' {
  declare module.exports: $Exports<'rollbar/src/browser/logger'>;
}
declare module 'rollbar/src/browser/plugins/jquery.js' {
  declare module.exports: $Exports<'rollbar/src/browser/plugins/jquery'>;
}
declare module 'rollbar/src/browser/predicates.js' {
  declare module.exports: $Exports<'rollbar/src/browser/predicates'>;
}
declare module 'rollbar/src/browser/rollbar.js' {
  declare module.exports: $Exports<'rollbar/src/browser/rollbar'>;
}
declare module 'rollbar/src/browser/rollbarWrapper.js' {
  declare module.exports: $Exports<'rollbar/src/browser/rollbarWrapper'>;
}
declare module 'rollbar/src/browser/shim.js' {
  declare module.exports: $Exports<'rollbar/src/browser/shim'>;
}
declare module 'rollbar/src/browser/snippet_callback.js' {
  declare module.exports: $Exports<'rollbar/src/browser/snippet_callback'>;
}
declare module 'rollbar/src/browser/telemetry.js' {
  declare module.exports: $Exports<'rollbar/src/browser/telemetry'>;
}
declare module 'rollbar/src/browser/transforms.js' {
  declare module.exports: $Exports<'rollbar/src/browser/transforms'>;
}
declare module 'rollbar/src/browser/transport.js' {
  declare module.exports: $Exports<'rollbar/src/browser/transport'>;
}
declare module 'rollbar/src/browser/url.js' {
  declare module.exports: $Exports<'rollbar/src/browser/url'>;
}
declare module 'rollbar/src/notifier.js' {
  declare module.exports: $Exports<'rollbar/src/notifier'>;
}
declare module 'rollbar/src/queue.js' {
  declare module.exports: $Exports<'rollbar/src/queue'>;
}
declare module 'rollbar/src/rateLimiter.js' {
  declare module.exports: $Exports<'rollbar/src/rateLimiter'>;
}
declare module 'rollbar/src/rollbar.js' {
  declare module.exports: $Exports<'rollbar/src/rollbar'>;
}
declare module 'rollbar/src/server/logger.js' {
  declare module.exports: $Exports<'rollbar/src/server/logger'>;
}
declare module 'rollbar/src/server/parser.js' {
  declare module.exports: $Exports<'rollbar/src/server/parser'>;
}
declare module 'rollbar/src/server/predicates.js' {
  declare module.exports: $Exports<'rollbar/src/server/predicates'>;
}
declare module 'rollbar/src/server/rollbar.js' {
  declare module.exports: $Exports<'rollbar/src/server/rollbar'>;
}
declare module 'rollbar/src/server/transforms.js' {
  declare module.exports: $Exports<'rollbar/src/server/transforms'>;
}
declare module 'rollbar/src/server/transport.js' {
  declare module.exports: $Exports<'rollbar/src/server/transport'>;
}
declare module 'rollbar/src/telemetry.js' {
  declare module.exports: $Exports<'rollbar/src/telemetry'>;
}
declare module 'rollbar/src/transforms.js' {
  declare module.exports: $Exports<'rollbar/src/transforms'>;
}
declare module 'rollbar/src/utility.js' {
  declare module.exports: $Exports<'rollbar/src/utility'>;
}
declare module 'rollbar/test/api.test.js' {
  declare module.exports: $Exports<'rollbar/test/api.test'>;
}
declare module 'rollbar/test/apiUtility.test.js' {
  declare module.exports: $Exports<'rollbar/test/apiUtility.test'>;
}
declare module 'rollbar/test/browser.predicates.test.js' {
  declare module.exports: $Exports<'rollbar/test/browser.predicates.test'>;
}
declare module 'rollbar/test/browser.rollbar.test.js' {
  declare module.exports: $Exports<'rollbar/test/browser.rollbar.test'>;
}
declare module 'rollbar/test/browser.transforms.test.js' {
  declare module.exports: $Exports<'rollbar/test/browser.transforms.test'>;
}
declare module 'rollbar/test/browser.transport.test.js' {
  declare module.exports: $Exports<'rollbar/test/browser.transport.test'>;
}
declare module 'rollbar/test/browser.url.test.js' {
  declare module.exports: $Exports<'rollbar/test/browser.url.test'>;
}
declare module 'rollbar/test/notifier.test.js' {
  declare module.exports: $Exports<'rollbar/test/notifier.test'>;
}
declare module 'rollbar/test/queue.test.js' {
  declare module.exports: $Exports<'rollbar/test/queue.test'>;
}
declare module 'rollbar/test/rateLimiter.test.js' {
  declare module.exports: $Exports<'rollbar/test/rateLimiter.test'>;
}
declare module 'rollbar/test/server.predicates.test.js' {
  declare module.exports: $Exports<'rollbar/test/server.predicates.test'>;
}
declare module 'rollbar/test/server.rollbar.test.js' {
  declare module.exports: $Exports<'rollbar/test/server.rollbar.test'>;
}
declare module 'rollbar/test/server.transforms.test.js' {
  declare module.exports: $Exports<'rollbar/test/server.transforms.test'>;
}
declare module 'rollbar/test/server.transport.test.js' {
  declare module.exports: $Exports<'rollbar/test/server.transport.test'>;
}
declare module 'rollbar/test/telemetry.test.js' {
  declare module.exports: $Exports<'rollbar/test/telemetry.test'>;
}
declare module 'rollbar/test/transforms.test.js' {
  declare module.exports: $Exports<'rollbar/test/transforms.test'>;
}
declare module 'rollbar/test/utility.test.js' {
  declare module.exports: $Exports<'rollbar/test/utility.test'>;
}
declare module 'rollbar/vendor/JSON-js/cycle.js' {
  declare module.exports: $Exports<'rollbar/vendor/JSON-js/cycle'>;
}
declare module 'rollbar/vendor/JSON-js/json_parse_state.js' {
  declare module.exports: $Exports<'rollbar/vendor/JSON-js/json_parse_state'>;
}
declare module 'rollbar/vendor/JSON-js/json_parse.js' {
  declare module.exports: $Exports<'rollbar/vendor/JSON-js/json_parse'>;
}
declare module 'rollbar/vendor/JSON-js/json2.js' {
  declare module.exports: $Exports<'rollbar/vendor/JSON-js/json2'>;
}
declare module 'rollbar/vendor/JSON-js/json3.js' {
  declare module.exports: $Exports<'rollbar/vendor/JSON-js/json3'>;
}
declare module 'rollbar/webpack.config.js' {
  declare module.exports: $Exports<'rollbar/webpack.config'>;
}
