// flow-typed signature: cc398259bb4666158b2abef10e990243
// flow-typed version: <<STUB>>/rollbar-sourcemap-webpack-plugin_v^2.2.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollbar-sourcemap-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollbar-sourcemap-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollbar-sourcemap-webpack-plugin/dist/constants' {
  declare module.exports: any;
}

declare module 'rollbar-sourcemap-webpack-plugin/dist/helpers' {
  declare module.exports: any;
}

declare module 'rollbar-sourcemap-webpack-plugin/dist/RollbarSourceMapPlugin' {
  declare module.exports: any;
}

declare module 'rollbar-sourcemap-webpack-plugin/src/constants' {
  declare module.exports: any;
}

declare module 'rollbar-sourcemap-webpack-plugin/src/helpers' {
  declare module.exports: any;
}

declare module 'rollbar-sourcemap-webpack-plugin/src/RollbarSourceMapPlugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollbar-sourcemap-webpack-plugin/dist/constants.js' {
  declare module.exports: $Exports<'rollbar-sourcemap-webpack-plugin/dist/constants'>;
}
declare module 'rollbar-sourcemap-webpack-plugin/dist/helpers.js' {
  declare module.exports: $Exports<'rollbar-sourcemap-webpack-plugin/dist/helpers'>;
}
declare module 'rollbar-sourcemap-webpack-plugin/dist/RollbarSourceMapPlugin.js' {
  declare module.exports: $Exports<'rollbar-sourcemap-webpack-plugin/dist/RollbarSourceMapPlugin'>;
}
declare module 'rollbar-sourcemap-webpack-plugin/src/constants.js' {
  declare module.exports: $Exports<'rollbar-sourcemap-webpack-plugin/src/constants'>;
}
declare module 'rollbar-sourcemap-webpack-plugin/src/helpers.js' {
  declare module.exports: $Exports<'rollbar-sourcemap-webpack-plugin/src/helpers'>;
}
declare module 'rollbar-sourcemap-webpack-plugin/src/RollbarSourceMapPlugin.js' {
  declare module.exports: $Exports<'rollbar-sourcemap-webpack-plugin/src/RollbarSourceMapPlugin'>;
}
