// flow-typed signature: cc43a0356e59c4e032fccb281457f8a8
// flow-typed version: <<STUB>>/version-changelog_v^2.1.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'version-changelog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'version-changelog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'version-changelog/cli' {
  declare module.exports: any;
}

declare module 'version-changelog/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'version-changelog/cli.js' {
  declare module.exports: $Exports<'version-changelog/cli'>;
}
declare module 'version-changelog/index' {
  declare module.exports: $Exports<'version-changelog'>;
}
declare module 'version-changelog/index.js' {
  declare module.exports: $Exports<'version-changelog'>;
}
declare module 'version-changelog/test/test.js' {
  declare module.exports: $Exports<'version-changelog/test/test'>;
}
