// flow-typed signature: 68a85859a05839f8cabb96ce00932da4
// flow-typed version: <<STUB>>/web-app-manifest-loader_v^0.1.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web-app-manifest-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web-app-manifest-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web-app-manifest-loader/test/error-cases/invalid-json/expected-error' {
  declare module.exports: any;
}

declare module 'web-app-manifest-loader/test/error-cases/invalid-json/index' {
  declare module.exports: any;
}

declare module 'web-app-manifest-loader/test/error-cases/invalid-json/webpack.config' {
  declare module.exports: any;
}

declare module 'web-app-manifest-loader/test/error-cases/missing-image/expected-error' {
  declare module.exports: any;
}

declare module 'web-app-manifest-loader/test/error-cases/missing-image/index' {
  declare module.exports: any;
}

declare module 'web-app-manifest-loader/test/error-cases/missing-image/webpack.config' {
  declare module.exports: any;
}

declare module 'web-app-manifest-loader/test/error-cases/missing-src/expected-error' {
  declare module.exports: any;
}

declare module 'web-app-manifest-loader/test/error-cases/missing-src/index' {
  declare module.exports: any;
}

declare module 'web-app-manifest-loader/test/error-cases/missing-src/webpack.config' {
  declare module.exports: any;
}

declare module 'web-app-manifest-loader/test/index' {
  declare module.exports: any;
}

declare module 'web-app-manifest-loader/test/success-cases/basic/index' {
  declare module.exports: any;
}

declare module 'web-app-manifest-loader/test/success-cases/basic/webpack.config' {
  declare module.exports: any;
}

declare module 'web-app-manifest-loader/test/success-cases/inline-loaders/index' {
  declare module.exports: any;
}

declare module 'web-app-manifest-loader/test/success-cases/inline-loaders/webpack.config' {
  declare module.exports: any;
}

declare module 'web-app-manifest-loader/test/utils/directory-contains' {
  declare module.exports: any;
}

declare module 'web-app-manifest-loader/test/utils/get-sub-dirs-sync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web-app-manifest-loader/index' {
  declare module.exports: $Exports<'web-app-manifest-loader'>;
}
declare module 'web-app-manifest-loader/index.js' {
  declare module.exports: $Exports<'web-app-manifest-loader'>;
}
declare module 'web-app-manifest-loader/test/error-cases/invalid-json/expected-error.js' {
  declare module.exports: $Exports<'web-app-manifest-loader/test/error-cases/invalid-json/expected-error'>;
}
declare module 'web-app-manifest-loader/test/error-cases/invalid-json/index.js' {
  declare module.exports: $Exports<'web-app-manifest-loader/test/error-cases/invalid-json/index'>;
}
declare module 'web-app-manifest-loader/test/error-cases/invalid-json/webpack.config.js' {
  declare module.exports: $Exports<'web-app-manifest-loader/test/error-cases/invalid-json/webpack.config'>;
}
declare module 'web-app-manifest-loader/test/error-cases/missing-image/expected-error.js' {
  declare module.exports: $Exports<'web-app-manifest-loader/test/error-cases/missing-image/expected-error'>;
}
declare module 'web-app-manifest-loader/test/error-cases/missing-image/index.js' {
  declare module.exports: $Exports<'web-app-manifest-loader/test/error-cases/missing-image/index'>;
}
declare module 'web-app-manifest-loader/test/error-cases/missing-image/webpack.config.js' {
  declare module.exports: $Exports<'web-app-manifest-loader/test/error-cases/missing-image/webpack.config'>;
}
declare module 'web-app-manifest-loader/test/error-cases/missing-src/expected-error.js' {
  declare module.exports: $Exports<'web-app-manifest-loader/test/error-cases/missing-src/expected-error'>;
}
declare module 'web-app-manifest-loader/test/error-cases/missing-src/index.js' {
  declare module.exports: $Exports<'web-app-manifest-loader/test/error-cases/missing-src/index'>;
}
declare module 'web-app-manifest-loader/test/error-cases/missing-src/webpack.config.js' {
  declare module.exports: $Exports<'web-app-manifest-loader/test/error-cases/missing-src/webpack.config'>;
}
declare module 'web-app-manifest-loader/test/index.js' {
  declare module.exports: $Exports<'web-app-manifest-loader/test/index'>;
}
declare module 'web-app-manifest-loader/test/success-cases/basic/index.js' {
  declare module.exports: $Exports<'web-app-manifest-loader/test/success-cases/basic/index'>;
}
declare module 'web-app-manifest-loader/test/success-cases/basic/webpack.config.js' {
  declare module.exports: $Exports<'web-app-manifest-loader/test/success-cases/basic/webpack.config'>;
}
declare module 'web-app-manifest-loader/test/success-cases/inline-loaders/index.js' {
  declare module.exports: $Exports<'web-app-manifest-loader/test/success-cases/inline-loaders/index'>;
}
declare module 'web-app-manifest-loader/test/success-cases/inline-loaders/webpack.config.js' {
  declare module.exports: $Exports<'web-app-manifest-loader/test/success-cases/inline-loaders/webpack.config'>;
}
declare module 'web-app-manifest-loader/test/utils/directory-contains.js' {
  declare module.exports: $Exports<'web-app-manifest-loader/test/utils/directory-contains'>;
}
declare module 'web-app-manifest-loader/test/utils/get-sub-dirs-sync.js' {
  declare module.exports: $Exports<'web-app-manifest-loader/test/utils/get-sub-dirs-sync'>;
}
