// flow-typed signature: b21c39aa78ec24e8aa9f7e8b1f6eb28d
// flow-typed version: <<STUB>>/withinviewport_v^2.0.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'withinviewport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'withinviewport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'withinviewport/jquery.withinviewport' {
  declare module.exports: any;
}

declare module 'withinviewport/withinviewport' {
  declare module.exports: any;
}

// Filename aliases
declare module 'withinviewport/jquery.withinviewport.js' {
  declare module.exports: $Exports<'withinviewport/jquery.withinviewport'>;
}
declare module 'withinviewport/withinviewport.js' {
  declare module.exports: $Exports<'withinviewport/withinviewport'>;
}
